apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: cnpg-postgresql
spec:
  images:
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
